apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudep1
  name: ashudep1 # name of deployment 
spec:
  replicas: 1 # number of Pod we want 
  selector:
    matchLabels:
      app: ashudep1
  strategy: {}
  template: # template 
    metadata:
      creationTimestamp: null
      labels:
        app: ashudep1
    spec:
      containers:
      - image: dockerashu/nodeapp:v1
        name: nodeapp
        resources: {}
status: {}
