apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashunode
  name: ashunode
spec:
  containers:
  - image: dockerashu/nodeapp:v1
    name: ashunode
    ports:
    - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
