apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupodx1
  name: ashupodx1 # name of pod 
spec:
  imagePullSecrets: # calling secret from current namespace
  - name: ashuimgsec # name of secret 
  containers:
  - command:
    - ping
    - localhost
    image: phx.ocir.io/axmbtg8judkl/alpine:v1 # ocir image 
    name: ashupodx1 # name 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
