apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashutoshhpod1
  name: ashutoshhpod1
  namespace: tasks
spec:
  containers:
  - command:
    - ping
    - fb.com
    image: busybox
    name: ashutoshhpod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
